name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Test
        run: |
          ./gradlew clean build test

      - name: Build Docker Image
        run: |
          docker build -t trollparts-app .

      - name: Push Docker Image to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login trollpartsacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker tag trollparts-app trollpartsacr.azurecr.io/trollparts-app
          docker push trollpartsacr.azurecr.io/trollparts-app
